[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "claude-logging"
version = "0.1.0"
authors = [
    {name = "Antonio Cuni"}
]
description = "Save logs of claude code, and convert them into HTML"
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Terminals",
    "Topic :: Text Processing :: Markup :: HTML",
]
keywords = ["claude", "logging", "ansi", "terminal", "html", "conversion"]

[project.urls]
"Homepage" = "https://github.com/antocuni/claude-logging"
"Bug Tracker" = "https://github.com/antocuni/claude-logging/issues"

[project.scripts]
claude-logging = "claude_logging.__main__:main"

[tool.setuptools]
packages = ["claude_logging"]

[[tool.setuptools.ext-modules]]
name = "claude_logging.pytermdump"
sources = ["claude_logging/pytermdump.c"]
extra-compile-args = ["-Wall"]
py-limited-api = true  # Use the stable ABI

[tool.cibuildwheel]
# Build options
build = "cp38-* cp39-* cp310-* cp311-* cp312-*"  # These are still needed for cibuildwheel
# Skip PyPy builds since we have a C extension
skip = "pp*"
# Make sure we test the package after building
test-command = "python -c \"import claude_logging; from claude_logging import pytermdump\""
# Use the stable ABI for compatibility across Python versions
build-frontend = {name = "pip", args = ["--config-settings=--global-option=--py-limited-api=cp38"]}
# By default, build with stable ABI for wide Python compatibility
manylinux-x86_64-image = "manylinux2014"
manylinux-i686-image = "manylinux2014"
